### ISSUE TITLE
Random segfaults

### ISSUE THREAD

**Issue by jdziemidowicz** [eustas/ngx_brotli#12]
My environment:
- Debian stretch
- libbrotli 1.0.3 from Debian backports
- nginx 1.13.12 backported by me from Debian testing
- ngx_brotli at f1fcc845611855855fbd34142840e947f161d486 using the system libbrotli

While in general it works, nginx workers segfault randomly. Unfortunately I am unable to reliably reproduce it myself yet, only throwing some real traffic at it manifests the problem.

Disabling brotli solved the problem with this build for me. I'll try to debug this further.

**Comment by eustas** [comment]
Hi. Could you try https://github.com/eustas/ngx_brotli/tree/fix-clean

I've found that interrupted requests caused segfaults just yesterday...

**Comment by jdziemidowicz** [comment]
For a start, I was able to reproduce segfaults with interrupted request.

```
dd if=/dev/urandom of=test.txt bs=1M count=500
wget --header='Accept-Encoding: br' -O /dev/null -S example.com/test.txt
```

Hit ctrl-c during the transfer and it segfaults immediately. Will try to rebuild with mentioned patch next.

**Comment by jdziemidowicz** [comment]
The fix-clean branches fixes above test. Also I haven't seen a single segfault on real traffic with this branch.

**Comment by eustas** [comment]
Thanks for checking. Going to merge it to master very soon and release a new tag.
