### ISSUE TITLE
Written data not fully flushed on socket

### ISSUE THREAD

**Issue by omarkilani** [eustas/ngx_brotli#14]
Hi eustas,

We were running ngx_brotli and saw some strange issues every maybe 0.01% of requests where nginx 'lied' about having completed a request (as in, log entry was written to access_log) in 4ms yet the connection was left open and written data was not fully 'flushed' to the client.

After 90 seconds (our proxy_*_timeout value) the connection was dropped.

Not really sure how to debug it since it was completely random. But removing ngx_brotli from our nginx build resolved the issue.

**Comment by eustas** [comment]
Well, at least we have point to start to unwind - we can try to catch the moment when connection is dropped.
For reproduction it would be nice to find the minimal filter stack with which the things go wrong...

**Comment by omarkilani** [comment]
It’s possible this is related to https://github.com/eustas/ngx_brotli/issues/11 but because we run a very high connected client count it’s hard to tell.

I’ll try and provide a minimal configuration soon.

**Comment by eustas** [comment]
Hello, @omarkilani. Could you test if #16 fixes the problem, please. Thanks.

**Comment by omarkilani** [comment]
Hi @eustas, I'll build this today and do some testing.

Do you know which ngx_brotli companies like Dropbox are using?

E.g. https://blogs.dropbox.com/tech/2017/09/optimizing-web-servers-for-high-throughput-and-low-latency/

Claims they're using nginx and brotli. But are they using the old module with an old brotli lib?

**Comment by eustas** [comment]
I have some statistics generated from HttpArchive data (https://httparchive.org/)
According to that statistics 15.4% of compressed requests are served with brotli.
The biggest producers are (not sorted):
 * facebook
 * googleapis (fonts)
 * doubleclick (ads)
 * youtube
 * cloudflare (site serving)
 * yandex (?)

The most web servers (software), excluding mentioned producers (not sorted):
 * CDN77
 * nginx
 * Apache
 * LiteSpeed
 * Akamai

**Comment by denji** [comment]
@omarkilani DropBox for brotli decoder uses Rust versions.

**Comment by omarkilani** [comment]
Hi @eustas

We’ve been running with the fix for over 24 hours without issues. I believe this issue is resolved.

I’ll update if it breaks again. :)
