### ISSUE TITLE
Libbrotlienc not found

### ISSUE THREAD

**Issue by alpiua** [eustas/ngx_brotli#15]
Was trying to build nginx with this fork, unsuccessfully.

What i did:
```
cd /opt/lib && git clone https://github.com/eustas/ngx_brotli.git && cd ngx_brotli && git submodule update --init
cd /opt/lib && git clone https://github.com/bagder/libbrotli.git && cd libbrotli
./autogen.sh
./configure
make && make install
```
then make nginx with 

```
--prefix=/usr/share/nginx \
--sbin-path=/usr/sbin/nginx \
--modules-path=/usr/lib64/nginx/modules \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--http-client-body-temp-path=/var/lib/nginx/tmp/client_body \
--http-proxy-temp-path=/var/lib/nginx/tmp/proxy \
--http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi \
--http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi \
--http-scgi-temp-path=/var/lib/nginx/tmp/scgi \
--pid-path=/run/nginx.pid \
--lock-path=/run/lock/subsys/nginx \
--user=nginx \
--group=nginx \
--with-file-aio \
--with-threads \
--with-http_v2_module \
--with-http_ssl_module \
--with-http_sub_module \
--with-http_gzip_static_module \
--with-http_stub_status_module \
--with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23' \
--with-ld-opt='-Wl,-z,relro -Wl,-E' \
--with-openssl=/opt/lib/openssl-1.0.2o	 \
--with-openssl-opt='enable-tlsext zlib no-ssl2 no-shared -fpic' \
--add-module=/opt/lib/ngx_pagespeed \
--add-module=/opt/lib/ngx_brotli
```

after install nginx can't start because of 

> /usr/sbin/nginx: error while loading shared libraries: libbrotlienc.so.0: cannot open shared object file: No such file or directory

With original google/ngx_brotli all this works smoothy

**Comment by eustas** [comment]
Hello. I'll dig into this soon.
A brief mark - you don't need bagder/libbrotli anymore; brotli source is cloned into ngx_brotli/deps directory.

**Comment by eustas** [comment]
The problem seems to be [here](https://github.com/eustas/ngx_brotli/blob/master/config#L152).
Scripts sees brotli installed in usr/local and tries to use provided library -> something goes wrong (library does not exist, or not discoverable, etc.).

Try to uninstall brotli / remove `/usr/local/include/brotli/encode.h` and recompile nginx.

**Comment by denji** [comment]
@eustas Please remove gitmodules `https://github.com/nginx/nginx.git` or use optional for travis-ci. Overhead rerun with `brew install --HEAD nginx...`

**Comment by eustas** [comment]
Okay. I thought I've already removed it (https://github.com/eustas/ngx_brotli/pull/10/commits/cf8a3853368460456896073ef9d393a54632d9e8). But it somehow survived...

**Comment by denji** [comment]
I think this issue can be closed?

**Comment by eustas** [comment]
@alpi-ua fell free to reopen, if the problem still exists.
