### ISSUE TITLE
you are the reference implementation, PR?

### ISSUE THREAD

**Issue by tttp** [eustas/ngx_brotli#17]
Hi,
your implementation seems to have become the de facto reference. At least you are maintaining it, google isn't.

Any plan to PR all your improvements?

**Comment by eustas** [comment]
Hi. It was a very hot summer, both literally and figural - was working hard on PIK, preparing it for JPEG-XL proposal. Starting from September, I'm back to brotli & co.

I plan to grab appropriate PRs from google/nginx_brotli, and some useful stuff from other branches, when I have time.

Also I plan to negotiate with google/nginx_brotli to get control over it, so it will be a less confusing story for users.

**Comment by tttp** [comment]
Great news, and welcome back ;)

**Comment by Exagone313** [comment]
The CLA may be a problem for merging back in the older project. Imho they could update their README to point to this repository.

**Comment by eustas** [comment]
There are 3 commits / authors I need to check / ask for signing CLA.
Technically, it is possible to rewrite the commit history in a way, that places commits of all authors who does not sign CLA at the end of the chain, and tag / pull at the "clean" commit... hopefully, we would not need to do this.

**Comment by eustas** [comment]
At last, reordered the commit sequence and merged the "approved" part of fork to google/ngx_brotli =)
