### ISSUE TITLE
Releases missing submodules

### ISSUE THREAD

**Issue by technion** [eustas/ngx_brotli#20]
Hi,

Let me start by saying, thanks a tonne for keeping this fork alive.

It seems like the "release" build doesn't contain what's needed to compile. Specifically I'm seeing this error:
```
./configure: error: Brotli library is missing from the ./ngx_brotli-0.1.2/deps/brotli/c directory.

Please make sure that the git submodule has been checked out:

    cd ./ngx_brotli-0.1.2 && git submodule update --init && cd /nginx-libressl/src/nginx-1.14.0
```
It reads like it has an obvious fix, but the advice given requires we be working with 
```
$ wget https://github.com/eustas/ngx_brotli/archive/v0.1.2.tar.gz
$ tar zxvf v0.1.2.tar.gz
$ cd ngx_brotli-0.1.2/
$ git submodule update --init
fatal: not a git repository (or any of the parent directories): .git
$ git status
fatal: not a git repository (or any of the parent directories): .git
```

I'm not sure what the trick to solving this is but apparently Micropython solved it:

https://github.com/micropython/micropython/issues/2952#issuecomment-324200260

**Comment by Exagone313** [comment]
You should use `git clone` to download. Also you can dynamically link to system brotli instead of building it.

**Comment by denji** [comment]
@eustas Add assets bundled with Git-submodules https://github.com/eustas/ngx_brotli/releases
