### ISSUE TITLE
sufficient buffer space?

### ISSUE THREAD

**Issue by setharnold** [eustas/ngx_brotli#21]
https://github.com/eustas/ngx_brotli/blob/28ce18d2c21a7582549d6ffc471cb1891225e64d/src/ngx_http_brotli_static_module.c#L137

Hello, I couldn't quickly find documentation on the `ngx_http_map_uri_to_path()` api, so please forgive the potentially naive question. Does the code properly verify that there's sufficient space at `p` to accept these writes?

Thanks

**Comment by eustas** [comment]
Hello. The last parameter is "reserved" - i.e. how much extra space to allocate.
`sizeof(".br")` is 4 (including \0 terminator), so we request `sizeof(".br") - 1` because terminator is not "extra" =)
