### ISSUE TITLE
not checking entire 'br' string?

### ISSUE THREAD

**Issue by setharnold** [eustas/ngx_brotli#22]
https://github.com/eustas/ngx_brotli/blob/28ce18d2c21a7582549d6ffc471cb1891225e64d/src/ngx_http_brotli_static_module.c#L326

Hello, this appears to be checking specifically for a `b` or `B`: `sizeof("br") - 2` is `1`.

If a header specifically included only a `b` here, I think the subsequent `p += sizeof("br")-1;` would jump past the end of the header.

Thanks

**Comment by kravietz** [comment]
@eustas  I would recommend that you register the repo with https://scan.coverity.com/ and https://lgtm.com/ which should detect more issues like this.

**Comment by eustas** [comment]
Will fix it soon. Thanks. Also will setup coverity integration...

**Comment by eustas** [comment]
@sboukortt

**Comment by eustas** [comment]
Fixed in upstream
