### ISSUE TITLE
brotli 1.0.6+

### ISSUE THREAD

**Issue by denji** [eustas/ngx_brotli#24]
https://github.com/google/brotli/releases/latest
* https://github.com/google/brotli/releases/tag/v1.0.5
* https://github.com/google/brotli/releases/tag/v1.0.6
* https://github.com/google/brotli/releases/tag/v1.0.7

> improve q=1 compression on small files
> add rolling-composite-hasher for large-window mode
> fix unaligned 64-bit accesses on AArch32
> add ASAN/MSAN unaligned read specializations

**Comment by eustas** [comment]
Yup, will pull soon.

**Comment by centminmod** [comment]
or 1.0.7 https://github.com/google/brotli/releases/tag/v1.0.7 ?

**Comment by sknight80** [comment]
Hi. Any updates on this?

**Comment by centminmod** [comment]
@eustas indeed due for an update :)

**Comment by Yinchie** [comment]
update?

**Comment by ezar** [comment]
Please!

**Comment by NotTsunami** [comment]
Issue can be closed now. 1.0.7 has been pulled in.
