### ISSUE TITLE
How to install brotly_FILTER_module?

### ISSUE THREAD

**Issue by davidmz** [eustas/ngx_brotli#25]
I am trying to add brotly to nginx using the FreeBSD www/nginx port (https://www.freshports.org/www/nginx/). I selected 'brotli' in port configuration and got compiled nginx with the following flags:

\# nginx -V
nginx version: nginx/1.14.2
built with OpenSSL 1.0.2p  14 Aug 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --add-module=/usr/ports/www/nginx/work/ngx_cache_purge-2.3 --with-debug --modules-path=/usr/local/libexec/nginx --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_v2_module --with-http_auth_request_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-pcre --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_geoip_module=dynamic --with-stream=dynamic **--add-dynamic-module=/usr/ports/www/nginx/work/ngx_brotli-8104036** --add-dynamic-module=/usr/ports/www/nginx/work/echo-nginx-module-c65f5c6

As you can see, the ngx_brotli module is here. But when I trying to add `brotli on;` directive to my 'server' section, I getting message `nginx: [emerg] unknown directive "brotli" in /www/htdocs/nginx.conf:166`.

It looks like I have only static version of module but not filter. What can I do to fix this?

**Comment by denji** [comment]
nginx.conf

```nginx
load_module modules/ngx_brotli.so;
...

user ...
worker_processes ..
....
```

**Comment by denji** [comment]
##### nginx.conf

```nginx
load_module modules/ngx_http_brotli_static_module.so;
load_module modules/ngx_http_brotli_filter_module.so;
...

user ...
worker_processes ..
....
```

**Comment by davidmz** [comment]
Thank you very much, @denji! It works now.
