### ISSUE TITLE
Append "Accept-Encoding" to an existing vary header, instead of always adding a new vary header.

### ISSUE THREAD

**Issue by ampaze** [eustas/ngx_brotli#26]
The current mechanism of simply adding a vary header, can lead to something like this

```
vary: Accept-Encoding
vary: X-Requested-With
```

Which in turn, because of this bug https://trac.nginx.org/nginx/ticket/1423 leads to
proxy_cache_key not working correctly.

The gzip module has the same issue, but as a lot more browsers support gzip, it is not as often a visible problem.

Just to clarify what the result can look like:
![image](https://user-images.githubusercontent.com/758593/51174671-a7379e80-18b8-11e9-97e5-eee98035a110.png)

As the Nginx ticket is not really worked on, maybe this can be fixed here, by appending Accept-Encoding to an existing vary header, if one exist?

```
vary: X-Requested-With, Accept-Encoding
```

**Comment by eustas** [comment]
Moved to the upstream
