### ISSUE TITLE
Accept-Encoding q-value of 0 is not honored

### ISSUE THREAD

**Issue by ampaze** [eustas/ngx_brotli#27]
When the request includes for example

```accept-encoding: gzip, deflate, br;q=0```

the answer is still using brotli, even though the accept-encoding header says don't send me brotli.

**Comment by eustas** [comment]
Hello, thanks for reporting. I'll check / fix as soon as I have free cycles (late February, I suppose).

**Comment by denji** [comment]
https://jakearchibald.github.io/accept-encoding-range-test/

**Comment by denji** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3

**Comment by NotTsunami** [comment]
I'm not sure about the disconnect from this and the Google repository, however when/if a patch is received for this, it should be merged upstream so we can be standard-compliant.

**Comment by eustas** [comment]
Moved to the upstream
