### ISSUE TITLE
100% nginx usage

### ISSUE THREAD

**Issue by kapouer** [eustas/ngx_brotli#30]
Hi, on debian/buster,
nginx 1.14.2
libbrotli 1.0.7
your latest ngx_brotli module, configured with
```
brotli on;

brotli_comp_level 6;
brotli_buffers 16 8k;
brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
```

After several requests (browsing several web sites) nginx quickly goes to 100% cpu load and stays there... If i set `brotli off` it doesn't happen.

The full configuration is
https://github.com/pageboard/proxy/tree/master/nginx

**Comment by eustas** [comment]
Will check that soon.

**Comment by HansVanEijsden** [comment]
I have the same issue, unfortunately. Is there any solution?

**Comment by kapouer** [comment]
Not that i know of. I disabled it for now.

**Comment by StirStudios** [comment]
We have the same issue. We have also experimented with a number of different settings and still we get the CPU spikes.

**Comment by HansVanEijsden** [comment]
Thanks for the feedback! After 12 hours of testing I also had to disable the module. I also tried the latest Brotli 1.0.7 but still the same hangs. It's a pity because it really gives me performance gains.. let me know if you need more information and if I can help (I'm not a coder though, but ISP).

**Comment by hroost** [comment]
Hi, is there any news?
Does this issue also happens on previous builds?

**Comment by eustas** [comment]
Moved to upstream
