### ISSUE TITLE
Build only ngx_http_brotli_static_module

### ISSUE THREAD

**Issue by alexxxnf** [eustas/ngx_brotli#31]
Hi @eustas,

Thank you very much for your work!

Is there a way to build only ngx_http_brotli_static_module without ngx_http_brotli_filter_module?

**Comment by denji** [comment]
## Modules dynamically:
```nginx
load_module modules/ngx_http_brotli_static_module.so;
# load_module modules/ngx_http_brotli_filter_module.so;
```

**Comment by alexxxnf** [comment]
@denji,

Thanks for the suggestion, but this is not exactly what I need.

This approach still takes time to build both modules. Also, I was hoping to get a single small statically linked executable.

**Comment by dvershinin** [comment]
@alexxxnf obviously you can achieve this through editing `config` before compilation, just trim it after [here](https://github.com/eustas/ngx_brotli/blob/master/config#L53) (then you will be only compiling the static module defined at the top)

**Comment by eustas** [comment]
Will take a look if there is a way to pass the args to "plugin" config.

**Comment by eustas** [comment]
There is no official way to pass the params.
So there are 2 options: split modules, i.e. create separate dirs with configs, or pass an option as environment variable.

**Comment by eustas** [comment]
will be fixed in upstream soon
