### ISSUE TITLE
Supported file types list

### ISSUE THREAD

**Issue by lidoma** [eustas/ngx_brotli#32]
Hi
Is there any official list of the Brotli supported file types?

**Comment by denji** [comment]
/etc/nginx/mime.types

http://nginx.org/en/docs/http/ngx_http_core_module.html#types
https://github.com/eustas/ngx_brotli#brotli_types (default: text/html)

**Comment by dvershinin** [comment]
There isn't, but the following is a list of well compressible formats MIME types:

       image/svg+xml
       application/x-font-ttf
       image/vnd.microsoft.icon
       application/x-font-opentype
       application/json
       font/eot
       application/vnd.ms-fontobject
       application/javascript
       font/otf
       application/xml
       application/xhtml+xml
       text/javascript
       application/x-javascript
       text/plain
       application/x-font-truetype
       application/xml+rss
       image/x-icon
       font/opentype
       text/css
       image/x-win-bitmap

Quoted from [blog post on configuring ngx_brotli in CentOS](https://www.getpagespeed.com/server-setup/nginx/install-nginx-with-brotli-module-in-centos-redhat-7)

**Comment by lidoma** [comment]
Thanks, @dvershinin. However, After reading a few blog posts, I reached this list.
```
application/atom+xml
application/geo+json
application/javascript
application/json
application/ld+json
application/manifest+json
application/rdf+xml
application/rss+xml
application/vnd.ms-fontobject
application/wasm
application/x-font-opentype
application/x-font-truetype
application/x-font-ttf
application/x-javascript
application/x-web-app-manifest+json
application/xhtml+xml
application/xml
application/xml+rss
font/eot
font/opentype
font/otf
image/bmp
image/svg+xml
image/vnd.microsoft.icon
image/x-icon
image/x-win-bitmap
text/cache-manifest
text/calendar
text/css
text/javascript
text/markdown
text/plain
text/vcard
text/vnd.rim.location.xloc
text/vtt
text/x-component
text/x-cross-domain-policy
text/xml
```
