### ISSUE TITLE
unbrotli?

### ISSUE THREAD

**Issue by dvershinin** [eustas/ngx_brotli#36]
Would it be possible to achieve/implement the same thing as what [gunzip](http://nginx.org/en/docs/http/ngx_http_gunzip_module.html#gunzip) module does, in regards with Brotli?

Just some idea how gunzip can be immediately useful first:

Say, you proxy a site with NGINX, and overwrite `Accept-Encoding` with `gzip` in order for the upstream to always return compress data
Then the value of `proxy_buffers` can be greatly reduced because you always know the response is rather small, essentially *reducing RAM usage*.
And with gunzip applied in NGINX, you still get to serve the clients who requested non-compressed resource.

We can't do the same trick with Brotli, as there is no equivalent module which would auto-decompress upstream response for clients which indicate their preference in no compression.

E.g. for a Magento 2 page which emits 512K worth of HTML, which compresses to under 50K with Brotli:

```
location / {
    proxy_pass foo;
    proxy_set_header Accept-Encoding br;
    unbrotli on;
    proxy_buffers 12 4k;  
    proxy_http_version 1.1;
}
```

instead of:

```
location / {
    proxy_pass foo;
    proxy_buffers 128 4k; # has to be set high because we don't know if upstream returns compressed/not
    proxy_http_version 1.1;
}
```

Sure, it implies delivering uncompressed response to gzip clients, but that may be OK to same folks (myself included), considering the [vast support of Brotli](https://caniuse.com/#feat=brotli) in browsers nowadays.

**Comment by eustas** [comment]
Will take a look, how it is done in gunzip. Perhaps it requires collaboration with nginx developers... Something we've never succeeded before =(

**Comment by eustas** [comment]
Seems to be just another filter -> doable.

**Comment by eustas** [comment]
Will create issue in upstream repo.
