### ISSUE TITLE
ngx_brotli won't work in nginx-1.16.1

### ISSUE THREAD

**Issue by draskolnikova** [eustas/ngx_brotli#38]
@eustas 

I tried to debug problems with `ngx_brotli` modules at 1.16.1. This is my configuration :
```
nginx version: blinx/1.16.1
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --add-module=ngx_brotli --with-cc-opt='-g -O2 -fdebug-prefix-map=/home/mockbuild/nginx-1.16.1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' --with-openssl=boringssl --with-openssl-opt=enable-tls1_3
``` 

The module should be loaded correctly with nginx, but the browser encoding still `gzip` instead of `br`.  I am using Google Chrome latest stable OSX. Is it normal @eustas ? 

Checked out submodule deps using commit d6d98957ca8ccb1ef45922e978bb10efca0ea541

**Comment by kapouer** [comment]
By default, the [brotli](https://github.com/eustas/ngx_brotli/#brotli) directive is `off`, so unless you setup your nginx config, brotli won't be activated.

**Comment by draskolnikova** [comment]
@kapouer i have enable `brotli on;`, but the encoding still gzip.

**Comment by beaudh** [comment]
I'm running 1.16.1 without issue here on RHEL7 compatible OEL7.

@draskolnikova maybe include your compile output and what particular release or commit of of ngx_brotli you're building?

Also, it's not listed in your configure, but as you're using --with-compat I think this is still relevant, are you including any other pre or post built dynamic modules ( e.g. ngx_pagespeed )?

And of course, the obvious, are you directly connecting to the server or behind cloudflare or similar?

Are you seeing "br" as an option for encoding in accept-encoding header in chrome? what happens if you remove gzip and deflate and only request br?

**Comment by eustas** [comment]
This fork is merged back to google/ngx_brotli. Please recreate this issue there (if necessary).
