### ISSUE TITLE
Update to brotli 1.0.2 ?

### ISSUE THREAD

**Issue by centminmod** [eustas/ngx_brotli#4]
Any plans to update to use brotli 1.0.2 ?

**Comment by eustas** [comment]
I see no reason not to do so...
BTW 1.0.3 is coming =)

**Comment by eustas** [comment]
Done

**Comment by centminmod** [comment]
hehe.. that was fast ! thanks @eustas 👍

**Comment by jauderho** [comment]
Update to brotli 1.0.3? =)

**Comment by eustas** [comment]
I believe, rather to 1.0.4. There is a bug in 1.0.3 - some aarch64-to-armhf cross-compilers produce faulty code. Going to fix it on Monday, make a release and pick up it here.

**Comment by eustas** [comment]
Updated to v1.0.4 =)
