### ISSUE TITLE
$brotli_ratio is always empty

### ISSUE THREAD

**Issue by xabbu** [eustas/ngx_brotli#8]
Since the update of brotli to v1.0.1, the $brotli_ratio variable is always empty. It should contain the compression ratio achieved by the brotli filter module. It should work similar to $gzip_ratio. The old google/ngx_brotli module works as accepted. 

I created a simple "log_format" which shows $gzip_ratio and $brotli_ratio. 

log_format compressed '[$time_local] "$request" $status '
                                       '$body_bytes_sent gzip $gzip_ratio br $brotli_ratio';

It shows on a simple HTTP connection, that gzip is used. Since there is no brotli, the $brotli_ratio is empty. This is expected. 

[26/Feb/2018:20:20:19 +0100] "GET / HTTP/1.1" 200 396 gzip 1.59 br -

On a  HTTP/2 connection is brotli used, so there is no gzip. But the $brotli_ratio variable is still empty. 

[26/Feb/2018:20:23:44 +0100] "GET / HTTP/2.0" 200 289 gzip - br -

I did test it with nginx 1.13.6 and 1.13.9, also with brotli v1.0.1 and v1.0.2

**Comment by eustas** [comment]
Going to dig into this tomorrow.

**Comment by eustas** [comment]
I suppose, that updates of "ctx->bytes_out" has been lost during migration to new brotli API. Should be a one-line fix =)

**Comment by eustas** [comment]
Should be fixed. Please try and report if it is still broken =)
